lib/rtl_web/router.ex
# Docs: http://www.phoenixframework.org/docs/routing#section-the-endpoint-plugs
defmodule RTLWeb.Router do
  use RTLWeb, :router
  # Rollbax error handler - see #handle_errors()
  use Plug.ErrorHandler
  import RTLWeb.AuthPlugs, only: [load_current_user: 2]
  import RTLWeb.SentryPlugs, only: [ensure_logged_in: 2]
  import RTLWeb.LocalePlugs, only: [detect_locale: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    # Note: CSRF protection is DISABLED, so we rely on same-site cookies.
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :load_current_user
    plug :detect_locale
  end

  pipeline :admin do
    plug :ensure_logged_in
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :load_current_user
  end

  pipeline :graphql do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :load_current_user
    plug :set_absinthe_context
  end

  scope "/", RTLWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/your_data", HomeController, :your_data
    get "/test_error", HomeController, :test_error

    get "/help", HelpController, :index
    get "/help/collecting_videos", HelpController, :collecting_videos
    get "/help/coding_page", HelpController, :coding_page

    get "/auth/signup", AuthController, :signup
    post "/auth/signup", AuthController, :signup_submit
    get "/auth/login", AuthController, :login
    post "/auth/login", AuthController, :login_submit
    get "/auth/logout", AuthController, :logout
    get "/auth/request_email_confirm", AuthController, :request_email_confirm
    post "/auth/request_email_confirm", AuthController, :request_email_confirm_submit
    get "/auth/confirm_email", AuthController, :confirm_email
    get "/auth/request_password_reset", AuthController, :request_password_reset
    post "/auth/request_password_reset", AuthController, :request_password_reset_submit
    get "/auth/reset_password", AuthController, :reset_password
    post "/auth/reset_password", AuthController, :reset_password_submit

    get "/account/edit", UserController, :edit
    patch "/account/update", UserController, :update
    patch "/account/update_email", UserController, :update_email

    #
    # Admin- and superadmin-facing routes
    #

    scope "/admin", as: :admin do
      pipe_through :admin

      resources "/users", Admin.UserController
      resources "/projects", Admin.ProjectController, param: "project_uuid"

      resources "/project_admin_joins", Admin.ProjectAdminJoinController,
        only: [:create, :delete]

      scope "/projects/:project_uuid" do
        resources "/custom_blocks", Admin.CustomBlockController,
          only: [:index, :edit, :update, :delete], param: "label"
        get "/custom_blocks/export", Admin.CustomBlockController, :export
        get "/custom_blocks/import", Admin.CustomBlockController, :import
        post "/custom_blocks/import_submit", Admin.CustomBlockController, :import_submit

        resources "/prompts", Admin.PromptController,
          except: [:index, :show], param: "prompt_uuid"

        resources "/videos", Admin.VideoController, only: [:index, :delete]
        get "/videos/:video_id/code", Admin.VideoController, :code
        post "/videos/:video_id/mark_coded", Admin.VideoController, :mark_coded

        get "/export_videos", Admin.VideoExportController, :new
        get "/import_videos", Admin.VideoImportController, :new
        post "/import_videos", Admin.VideoImportController, :create
      end
    end

    #
    # Public-facing project-related routes
    #

    scope "/projects/:project_uuid" do
      get "/", ProjectController, :show

      resources "/prompts/:prompt_uuid/videos", VideoController, only: [:new, :create]
      get "/videos/thank_you", VideoController, :thank_you
      get "/videos/:id", VideoController, :show
      # Legacy URL for webcam recording page
      get "/share/prompts/:prompt_uuid/from_webcam/new", VideoController, :new

      get "/results/", ResultsController, :index
      get "/results/playlist", ResultsController, :playlist
    end

    # In dev, preview all "sent" emails at localhost:4000/sent_emails
    if Mix.env == :dev do
      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/api", RTLWeb do
    pipe_through :api

    post "/log", Api.LogController, :log
  end

  scope "/graphql" do
    pipe_through :graphql

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: RTLWeb.Graphql.Schema,
      json_codec: Jason

    forward "/", Absinthe.Plug,
      schema: RTLWeb.Graphql.Schema,
      json_codec: Jason
  end

  defp handle_errors(conn, data), do: RTLWeb.RollbarPlugs.handle_errors(conn, data)

  defp set_absinthe_context(conn, _) do
    Absinthe.Plug.put_options(conn, context: %{current_user: conn.assigns.current_user})
  end
end

lib/rtl_web/views/layout_view.ex
defmodule RTLWeb.LayoutView do
  use RTLWeb, :view

  def manage_or_view_project_path(conn) do
    project = conn.assigns.project
    current_user = conn.assigns.current_user

    if can_manage_project?(current_user, project),
      do: Routes.admin_project_path(conn, :show, project),
      else: Routes.project_path(conn, :show, project)
  end
end

lib/rtl_web/templates/layout/_gettext_js.html.eex
<%# I'm not sure what's the best-practice way to pass Gettext strings to JS code. %>
<%# For now we'll define all JS-relevant strings in the page header. %>
<%# Thanks to https://stackoverflow.com/a/48704265/1729692 %>
<script type="text/javascript">
  var translations = <%= raw Jason.encode!(%{
    "Please fill in your name." => gettext("Please fill in your name."),
    "Loading..." => gettext("Loading..."),
    "Error!" => gettext("Error!"),
    "Video info" => gettext("Video info"),
    "Speaker:" => gettext("Speaker:"),
    "Question:" => gettext("Question:"),
    "apply" => gettext("apply"),
    "Really delete this tag?" => gettext("Really delete this tag?"),
    "Make a selection in the timeline first." => gettext("Make a selection in the timeline first."),
    "Add a new tag" => gettext("Add a new tag"),
    "Really delete this tagging?" => gettext("Really delete this tagging?"),
    "That's all the clips we have for your search. Adjust your filters to see more." => gettext("That's all the clips we have for your search. Adjust your filters to see more."),
    "Clear all selected tags" => gettext("Clear all selected tags"),
    "We didn't find any results for that search." => gettext("We didn't find any results for that search."),
  }) %>;

  // Now in any JS file, I can call `gettext("the string to translate")`.
  // Any missing keys will raise an error (and in prod, will be reported to Rollbar).
  gettext = function(key) {
    if (translations[key]) {
      return translations[key];
    } else {
      throw("Error: Missing gettext key \""+key+"\"");
    }
  };
</script>

lib/rtl_web/templates/layout/_nav_links.html.eex
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= custom_block @conn, "navbar_logo" %>

  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar-content">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div id="navbar-content" class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <%= if @conn.assigns[:project] do %>
        <%= if @current_user do %>
          <%= link gettext("Dashboard"), to: Routes.admin_project_path(@conn, :show, @project), class: "nav-link #{active_if_current(@conn, Routes.admin_project_path(@conn, :show, @project))}" %>
        <% end %>

        <%= if project_setting(@project, "show_explore_link") do %>
          <%= link gettext("Explore"), to: Routes.results_path(@conn, :index, @project), class: "nav-link #{active_if_current(@conn, Routes.results_path(@conn, :index, @project))}" %>
        <% else %>
          <%= if RTL.Sentry.can_manage_project?(@current_user, @project) do %>
            <%= link raw(gettext("Explore") <> " <i class='icon text-danger'>lock</i>"),
              to: Routes.results_path(@conn, :index, @project),
              class: "nav-link u-nowrap #{active_if_current(@conn, Routes.results_path(@conn, :index, @project))}" %>
          <% end %>
        <% end %>
      <% end %>
    </ul>

    <ul class="navbar-nav">

      <%= if @current_user do %>

        <li class="nav-item">
          <%= link gettext("Projects"), to: Routes.admin_project_path(@conn, :index), class: "nav-link #{active_if_current(@conn, Routes.admin_project_path(@conn, :index))} test-link-manage-project-list" %>
        </li>

        <%= if is_superadmin?(@current_user) do %>
          <li class="nav-item">
            <%= link gettext("Users"), to: Routes.admin_user_path(@conn, :index), class: "text-warning nav-link test-link-manage-user-list" %>
          </li>
        <% end %>

      <% end %>

      <li class="nav-item">
        <%= link gettext("Help"), to: Routes.help_path(@conn, :index), class: "nav-link" %>
      </li>

      <%= if @current_user do %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
            <%= icon "person" %> <%= gettext "Account" %>
            <span class="caret"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item em small"><%= gettext "Logged in as %{user}", user: @current_user.name %></div>
            <%= link gettext("Account settings"), to: Routes.user_path(@conn, :edit), class: "dropdown-item" %>
            <%= link icon("exit_to_app", gettext(" Log out")),
              to: Routes.auth_path(@conn, :logout),
              class: "dropdown-item text-danger test-logout-link" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link gettext("Log in"), to: Routes.auth_path(@conn, :login), class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link gettext("Sign up"), to: Routes.auth_path(@conn, :signup), class: "nav-link" %>
        </li>

      <% end %>

      <% current_locale = Gettext.get_locale(RTLWeb.Gettext) %>
      <% other_locales = Gettext.known_locales(RTLWeb.Gettext) -- [current_locale] %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
          <%= flag_for_locale(current_locale) %> <span class="caret"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= for locale <- other_locales do %>
            <%= link "#{flag_for_locale(locale)} #{String.upcase(locale)}", to: "?locale=#{locale}", class: "dropdown-item" %>
          <% end %>
        </div>
      </li>

    </ul>
  </div>
</nav>

lib/rtl_web/templates/layout/app.html.eex
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
      <%= if title = @conn.assigns[:page_title], do: "#{title} • " %>
      RTL
    </title>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <style><%= custom_block @conn, "custom_css" %></style>

    <%= if Mix.env() == :prod, do: render "_rollbar_js.html" %>
    <%= render "_gettext_js.html" %>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <%= render "_nav_links.html", Map.merge(%{conn: @conn}, @conn.assigns) %>

    <main>
      <div class="container-fluid">
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>

        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end %>

        <%= render @view_module, @view_template, assigns %>
      </div>
    </main>

    <footer><%= custom_block @conn, "footer" %></footer>
  </body>
</html>

lib/rtl_web/templates/layout/email.html.eex
<html>
  <head>
    <style>
    </style>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>